#!/usr/bin/zsh

rpath() { echo "$1" | rev | cut -d/ -f1 | rev }

if [[ -z "$1" ]]; then
  echo "Usage: $(rpath $0) <subvolume>"
  echo
  echo "Create a snapshot of a <subvolume> in"
  echo "/home/_snapshots/$(whoami)/@<subvolume>_<datetime>"
  exit 1
fi

mdtf=$(date +%Y%W%u-%H%M%S)
subname=$(rpath $1)
btrfs subvolume snapshot $1 /home/_snapshots/$(whoami)/@${subname}_${mdtf}
