#!/usr/bin/zsh

if [[ -z "$1" ]]; then
  bg='black'
  gs='#000000'
else
  bg='white'
  gs='#ffffff'
fi

gsettings set org.gnome.desktop.background primary-color $gs

cd ~/.conky
  rm theme
  ln -s themes/$bg theme
  ./build
cd

cd ~/Pictures/wallpaper
  gsettings set org.gnome.desktop.background picture-uri file://$(pwd)/$bg.jpg
cd
