#!/bin/bash

echo "
browserify
bunyan
csslint
forever
gulp-cli
hoodie-cli
htmlhint
jison
keybase
knex
less
mocha
n
nodemon
npm
pm2
postcss
semver
sitespeed.io
standard
tract
vantage
" | xargs npm i -g --cache-min 99999
