#!/usr/bin/env bash

set -euo pipefail

part="${1:-}"
if [[ -z "$part" ]]; then
  echo "Usage: $0 <partition>" >&2
  exit 64
fi

echo "==> Listing slots for $part"
slot=$(run0 systemd-cryptenroll "$part" \
  | tee /dev/stderr \
  | grep tpm2 \
  | head -n1 \
  | sed -E 's/\s+/,/g' \
  | cut -d, -f2)
echo

read -p "==> De-enroll slot $slot? [Yn]" confirm
if [[ -z "$confirm" || "$confirm" == "Y" || "$confirm" == "y" ]]; then
  echo "==> Re-enrolling TPM"
  # 0  = firmware
  # 5  = partition table for disk
  #      - not truly necessary but a useful warning mechanism
  # 7  = secure boot state incl certificates
  #      - kernel and bootloader are indirectly protected via this
  #        but without invalidation on updates
  # 12 = kernel command line
  #      - protects against editing it to bypass other auth systems
  runzero systemd-cryptenroll --wipe-slot="$slot" --tpm2-device=auto --tpm2-pcrs=0+5+7+12 "$part"
  echo
else
  echo "Abort."
  exit
fi
