#!/usr/bin/zsh

days="$2"
if [[ -z "$days" ]]; then
  days=1
fi

chan="$1"
if [[ -z "$chan" ]]; then
  chan="\#ualug"
fi

find ~/.vault/znclogs |grep $chan |tail -n$days |xargs cat
rsync -ar root@tanna.passcod.name:/var/lib/znc/log/ ~/.vault/znclogs/

