#!/usr/bin/zsh

days="$2"
if [[ -z "$days" ]]; then
  days=1
fi

chan="$1"
if [[ -z "$chan" ]]; then
  chan="\#ualug"
fi

for f in $(find ~/.vault/znclogs |grep $chan |tail -n$days); do
  echo -n :: 
  echo $f |rev|cut -d_ -f1-3 |cut -c5- |rev
  cat $f
  echo
done
