#!/usr/bin/env bash

set -euo pipefail

url="https://update.code.visualstudio.com/latest/linux-x64/insider"
target="$HOME/.local/share/vscode"
xattr="user.vscode.updatename"

mkdir -p "$target"
cd "$target"

echo -n "Fetching latest version: "
name=$(curl -sI "$url" | rg '^Location:' | rg -o 'code.+[.]tar[.]gz')
echo "$name"

echo -n "Checking current version: "
existing=$(getfattr --only-values -n "$xattr" "$(find . -type f -print -quit)" || true)
if [[ -z "$existing" ]]; then
  echo none
else
  echo "$existing"
  if [[ "$existing" == "$name" ]]; then
    echo "Already at latest version"
    exit
  fi
fi

echo -n "Deleting unversioned files: "
for topfile in $(ls -A); do
  if ! getfattr --only-values -n "$xattr" "$topfile" >/dev/null; then
    rm -rf "$topfile"
    echo -n "."
  fi
done
echo " DONE"

# fetch and extract
echo -n "Updating: "
curl -L "$url" \
  | tar xz --strip-components=1 --recursive-unlink --unlink-first
echo "DONE"

# mark all with 'version'
echo -n "Recording version: "
find . -exec setfattr -n "$xattr" -v "$name" '{}' \;
echo "DONE"

echo "== You’ll want to restart vscode now =="
